springdoc:
  api-docs:
    path: /api-docs.json
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  cache:
    disabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
